# Generated by Django 6.1 on 2026-08-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('TEXT', 'Texte'), ('TEXTAREA', 'Texte long'), ('RADIO', 'Choix unique'), ('CHECKBOX', 'Choix multiples'), ('SELECT', 'Liste déroulante'), ('NUMBER', 'Nombre'), ('EMAIL', 'Email'), ('DATE', 'Date'), ('YES_NO', 'Oui / Non')], max_length=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('publier', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulaire', to='campagne.campagne')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('valeur', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='formulaire.question')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='formulaire.formulaire')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='formulaire.sectionformulaire'),
        ),
    ]
