# Generated by Django 6.0.6 on 2026-08-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
