# Generated by Django 6.0.6 on 2026-08-19 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='candidature.candidature')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='formulaire.question')),
            ],
            options={
                'ordering': ['question__ordre', 'question__id'],
            },
        ),
        migrations.CreateModel(
            name='ReponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='formulaire.optionquestion')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_selectionnees', to='formulaire.reponsequestion')),
            ],
            options={
                'ordering': ['option__ordre', 'option__id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reponsequestion',
            constraint=models.UniqueConstraint(fields=('candidature', 'question'), name='unique_candidature_question'),
        ),
        migrations.AddConstraint(
            model_name='reponseoption',
            constraint=models.UniqueConstraint(fields=('reponse', 'option'), name='unique_reponse_option'),
        ),
    ]
