# Generated by Django 6.0.6 on 2026-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_reponsequestion_reponseoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
