# Generated by Django 6.0.6 on 2026-08-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagne', '0005_creneauri_nom'),
        ('candidature', '0004_convocationri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TECHNIQUE', 'Entretien technique'), ('MOTIVATION', 'Entretien motivation'), ('FINAL', 'Entretien final')], default='TECHNIQUE', help_text="Type d'entretien (Technique, Motivation, Final).", max_length=50)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', help_text="Statut actuel de la session d'entretien.", max_length=20)),
                ('date', models.DateField(help_text="Date de la session d'entretiens.")),
                ('heure_debut', models.TimeField(help_text='Heure de début de la session.')),
                ('heure_fin', models.TimeField(blank=True, help_text='Heure de fin estimée de la session.', null=True)),
                ('duree_minutes', models.PositiveIntegerField(default=45, help_text="Durée moyenne d'un passage en minutes.")),
                ('lieu', models.CharField(default='Simplon Sénégal', help_text='Lieu physique ou mention de visio-conférence.', max_length=255)),
                ('lien_visio', models.URLField(blank=True, default='', help_text='Lien de réunion en ligne (Google Meet, Teams, Zoom, etc.).', max_length=500)),
                ('notes', models.TextField(blank=True, default='', help_text="Objectifs, critères d'évaluation et consignes pour les jurys.")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(help_text='Campagne de recrutement associée.', on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='campagne.campagne')),
                ('jurys', models.ManyToManyField(blank=True, help_text="Membres du jury assignés à cette session d'entretien.", related_name='entretiens_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'entretien",
                'verbose_name_plural': "Sessions d'entretiens",
                'ordering': ['-date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='CreneauEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date spécifique si différente de la session parente.', null=True)),
                ('heure_debut', models.TimeField(help_text='Heure de début du passage.')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du passage.')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('CONFIRME', 'Confirmé'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='RESERVE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(blank=True, help_text='Candidat assigné à ce créneau horaire.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_entretien', to='candidature.candidature')),
                ('jurys', models.ManyToManyField(blank=True, help_text='Membres du jury affectés spécifiquement à ce créneau.', related_name='creneaux_jury', to=settings.AUTH_USER_MODEL)),
                ('entretien', models.ForeignKey(help_text="Session d'entretien parente.", on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='entretien.entretien')),
            ],
            options={
                'verbose_name': "Créneau d'entretien",
                'verbose_name_plural': "Créneaux d'entretiens",
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ConvocationEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TECHNIQUE', 'Entretien technique'), ('MOTIVATION', 'Entretien motivation'), ('FINAL', 'Entretien final')], default='TECHNIQUE', max_length=50)),
                ('date', models.DateField(help_text="Date de l'entretien.")),
                ('heure_debut', models.TimeField(help_text="Heure de début de l'entretien.")),
                ('heure_fin', models.TimeField(blank=True, help_text="Heure de fin de l'entretien.", null=True)),
                ('lieu', models.CharField(default='Simplon Sénégal', max_length=255)),
                ('lien_visio', models.URLField(blank=True, default='', max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('present', 'Présent'), ('absent', 'Absent'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='confirme', max_length=20)),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date et heure effectives d'envoi de la convocation par email.", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(help_text='Candidature convoquée.', on_delete=django.db.models.deletion.CASCADE, related_name='convocations_entretien', to='candidature.candidature')),
                ('creneau', models.ForeignKey(blank=True, help_text='Créneau horaire exact attribué.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocations', to='entretien.creneauentretien')),
                ('entretien', models.ForeignKey(help_text="Session d'entretien.", on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='entretien.entretien')),
            ],
            options={
                'verbose_name': 'Convocation à un entretien',
                'verbose_name_plural': 'Convocations aux entretiens',
                'ordering': ['date', 'heure_debut'],
                'constraints': [models.UniqueConstraint(fields=('entretien', 'candidature'), name='unique_candidature_par_entretien')],
            },
        ),
    ]
