# Generated by Django 6.0.6 on 2026-08-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0005_creneauri_nom'),
        ('entretien', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneauentretien',
            options={'ordering': ['heure_debut'], 'verbose_name': "Créneau d'entretien", 'verbose_name_plural': "Créneaux d'entretien"},
        ),
        migrations.AlterModelOptions(
            name='entretien',
            options={'ordering': ['-date', 'heure_debut'], 'verbose_name': "Session d'entretien", 'verbose_name_plural': "Sessions d'entretien"},
        ),
        migrations.CreateModel(
            name='QuestionEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(help_text='Intitulé de la question.', max_length=255)),
                ('type_question', models.CharField(choices=[('TEXT', 'Texte court'), ('TEXTAREA', 'Texte long'), ('NOTE', 'Note'), ('COMMENTAIRE', 'Commentaire'), ('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple')], default='TEXT', help_text='Type de réponse attendue.', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage des questions.")),
                ('obligatoire', models.BooleanField(default=False, help_text='Question obligatoire.')),
                ('note_max', models.PositiveIntegerField(default=10, help_text='Note maximale attribuable.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(help_text='Campagne de recrutement associée.', on_delete=django.db.models.deletion.CASCADE, related_name='questions_entretien', to='campagne.campagne')),
                ('entretiens', models.ManyToManyField(blank=True, help_text="Sessions d'entretien auxquelles cette question est associée.", related_name='questions_entretien', to='entretien.entretien')),
            ],
            options={
                'verbose_name': "Question d'entretien",
                'verbose_name_plural': "Questions d'entretien",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField(blank=True, default='', help_text='Réponse textuelle du jury.')),
                ('note', models.PositiveIntegerField(blank=True, help_text='Note attribuée par le jury.', null=True)),
                ('commentaire', models.TextField(blank=True, default='', help_text='Commentaire du jury.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entretien', models.ForeignKey(help_text="Session d'entretien concernée.", on_delete=django.db.models.deletion.CASCADE, related_name='reponses_entretien', to='entretien.entretien')),
                ('jury', models.ForeignKey(help_text='Membre du jury qui a répondu.', on_delete=django.db.models.deletion.CASCADE, related_name='reponses_jury', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='Question à laquelle le jury répond.', on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='entretien.questionentretien')),
            ],
            options={
                'verbose_name': "Réponse d'entretien",
                'verbose_name_plural': "Réponses d'entretien",
                'ordering': ['question__ordre', 'question__id'],
                'constraints': [models.UniqueConstraint(fields=('entretien', 'question', 'jury'), name='unique_reponse_entretien_question_jury')],
            },
        ),
    ]
