# Generated by Django 6.0.6 on 2026-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_name_user_last_name_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'Utilisateur Créé'), ('INVITATION_SENT', 'Invitation Envoyée'), ('ACCOUNT_ACTIVATED', 'Compte Activé'), ('LOGIN_SUCCESS', 'Connexion Réussie'), ('LOGIN_FAILED', 'Échec Connexion'), ('LOGOUT', 'Déconnexion'), ('PROFILE_COMPLETED', 'Profil Complété'), ('PASSWORD_RESET_REQUESTED', 'Demande Réinitialisation Mot de Passe'), ('PASSWORD_RESET_COMPLETED', 'Mot de Passe Réinitialisé')], max_length=50),
        ),
    ]
