# Generated by Django 6.1 on 2026-08-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagne', '0007_alter_campagne_id_alter_critereselection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Présent')], default='absent', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='campagne.campagne')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
    ]
