# Generated by Django 6.0.6 on 2026-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('present', 'Présent'), ('absent', 'Absent')], default='en_attente', max_length=20),
        ),
    ]
