# Generated by Django 6.0.6 on 2026-08-19 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0004_alter_campagne_criteres'),
        ('candidature', '0002_alter_candidature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='qr_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token unique sécurisé associé au candidat pour son QR code.', unique=True),
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RI', "Réunion d'Information"), ('TECHNIQUE', 'Entretien technique'), ('MOTIVATION', 'Entretien motivation'), ('FINAL', 'Entretien final')], default='RI', max_length=50)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(default='Simplon Sénégal', max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('present', 'Présent'), ('absent', 'Absent'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('presence_at', models.DateTimeField(blank=True, help_text='Date et heure exactes auxquelles la présence a été validée via le scan QR.', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='campagne.campagne')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='candidature.candidature')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
