# Generated by Django 6.0.6 on 2026-08-20 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0005_creneauri_nom'),
        ('candidature', '0003_candidature_qr_token_convocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvocationRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token unique sécurisé associé au QR code de la convocation RI.', unique=True)),
                ('statut', models.CharField(choices=[('absent', 'Absent'), ('present', 'Présent')], default='absent', max_length=20)),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date et heure de l'envoi de l'email de convocation.", null=True)),
                ('date_presence', models.DateTimeField(blank=True, help_text='Date et heure exactes auxquelles la présence a été validée via le scan QR.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations_ri', to='candidature.candidature')),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convocations', to='campagne.creneauri')),
                ('reunion_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='campagne.reunioninformation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('candidature', 'reunion_information'), name='unique_candidature_reunion_ri')],
            },
        ),
    ]
