# Generated by Django 6.1 on 2026-08-12 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('cloturee', 'Cloturée')], default='brouillon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CritereSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('id_campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='campagne.campagne')),
            ],
        ),
        migrations.AddField(
            model_name='campagne',
            name='id_referentiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referentiel', to='campagne.referentiel'),
        ),
    ]
