# Generated by Django 6.1 on 2026-08-19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunioninformation',
            name='campagne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reunion_information', to='campagne.campagne'),
        ),
        migrations.RemoveField(
            model_name='reunioninformation',
            name='begin_hour',
        ),
        migrations.RemoveField(
            model_name='reunioninformation',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='reunioninformation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reunioninformation',
            name='ri_date',
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='lieu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reunioninformation',
            name='titre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CreneauRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='campagne.reunioninformation')),
            ],
            options={
                'ordering': ['heure_debut'],
            },
        ),
    ]
