# Generated by Django 6.1 on 2026-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critereselection',
            name='id_campagne',
        ),
        migrations.AddField(
            model_name='critereselection',
            name='campagnes',
            field=models.ManyToManyField(related_name='criteres', to='campagne.campagne'),
        ),
    ]
