# Generated by Django 6.0.6 on 2026-08-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ri_date', models.DateField()),
                ('begin_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ri', to='campagne.campagne')),
            ],
        ),
    ]
