# Generated by Django 6.1 on 2026-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0002_remove_critereselection_id_campagne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campagne',
            old_name='id_referentiel',
            new_name='referentiel',
        ),
        migrations.RemoveField(
            model_name='critereselection',
            name='campagnes',
        ),
        migrations.AddField(
            model_name='campagne',
            name='criteres',
            field=models.ManyToManyField(related_name='criteres', to='campagne.critereselection'),
        ),
    ]
