# Generated by Django 6.0.6 on 2026-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0002_reunioninformation_and_creneau_ri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reunioninformation',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='reunioninformation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reunioninformation',
            name='lieu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reunioninformation',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
