# Generated by Django 6.0.6 on 2026-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0003_alter_reunioninformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='criteres',
            field=models.ManyToManyField(blank=True, related_name='campagnes', to='campagne.critereselection'),
        ),
    ]
