# Generated by Django 6.1 on 2026-08-12 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0003_rename_id_referentiel_campagne_referentiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='criteres',
            field=models.ManyToManyField(related_name='campagnes', to='campagne.critereselection'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='referentiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='campagne.referentiel'),
        ),
    ]
