# Generated by Django 4.2.11 on 2026-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0004_alter_campagne_criteres_alter_campagne_referentiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='criteres',
            field=models.ManyToManyField(null=True, related_name='campagnes', to='campagne.critereselection'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='critereselection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='referentiel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
