# Generated by Django 6.0.6 on 2026-08-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0004_alter_campagne_criteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneauri',
            name='nom',
            field=models.CharField(blank=True, default='', help_text='Nom du créneau ou du groupe (ex: Groupe matin, Groupe soir)', max_length=100),
        ),
    ]
