# Generated by Django 6.1 on 2026-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0004_alter_campagne_criteres_alter_campagne_referentiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='criteres',
            field=models.ManyToManyField(null=True, related_name='campagnes', to='campagne.critereselection'),
        ),
    ]
