# Generated by Django 6.1 on 2026-08-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0005_alter_campagne_criteres'),
        ('campagne', '0005_alter_campagne_criteres_alter_campagne_id_and_more'),
    ]

    operations = [
    ]
